const colorArrayNames = [
    "Naranja",
    "Naranja Claro",
    "Morado",
    "Amarrillo Claro",
    "Azul Claro",
    "Amarrilo",
    "Azul",
    "Amarillo",
    "Verde Claro",
    "Rojo",
    "Verde",
    "Verde",
    "Rojo Claro",
    "Azul Claro",
    "Verde",
    "Rosado",
    "Amarrillo",
    "Rojo",
    "Rojo",
    "Azul",
    "Verde Oscuro",
    "Morado",
    "Verde Oscuro",
    "Rojo Oscuro",
    "Morado Claro",
    "Amarillo Oscuro",
    "Morado",
    "Morado Claro",
    "Azul",
    "Verde",
    "Rosado",
    "Verde",
    "Rojo Claro",
    "Amarillo",
    "Verde",
    "Verde Oscuro",
    "Verde Claro",
    "Amarillo",
    "Verde",
    "Amarrillo Oscuro",
    "Rosado",
    "Amarillo",
    "Verde",
    "Azul",
    "Morado",
    "Rojo Claro",
    "Verde",
    "Rojo",
    "Azul Claro",
    "Azul",
];

export default colorArrayNames;